### PR TITLE
Added link to microservices article

### PR DESCRIPTION
**Pull request by knoxknox**
This article describes some aspects of migration to microservices.
It described OOD, DI, SOLID, Law of Demeter, Service Objects, etc..

### CODE REVIEW

**Comment by knoxknox** [comment]
+@iJackUA
Hi, could you look at this PR ?

**Comment by rennanoliveira** [comment]
I think this is a great article, but the current section it is added to is focusing on creating smaller classes and following TRUE, SOLID classes. The medium article goes even further, getting into microservices. Perhaps we could have a section about microservices, and drop the link there.

**Comment by iJackUA** [comment]
Thanks, this article looks interesting.

I really want to think about it more and eventually to create a separate section for detailed explanation and links per each aspect of SOLID and GRASP #31.
There is a TODO `Describe approaches like Form Model, Service Object, Context` and this article touches a lot of these.

Note for me: Make a note about "law of demeter" and rewrite examples in section http://rwdtow.stdout.in/#mixin-composition to emphasize usage in private interface

http://www.virtuouscode.com/2011/07/05/demeter-its-not-just-a-good-idea-its-the-law/

**Comment by iJackUA** [comment]
I'll merge it for now and add an issue to process it with more details #34

**Pull request merged**
